export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILTURE = "FETCH_POSTS_FAILTURE";

export const FETCH_CURRENT_POST_START = "FETCH_CURRENT_POST_START";
export const FETCH_CURRENT_POST_SUCCESS = "FETCH_CURRENT_POST_SUCCESS";
export const FETCH_CURRENT_POST_FAILTURE = "FETCH_CURRENT_POST_FAILTURE";
